# Generated by Django 5.2.3 on 2025-09-19 16:12

import helper.generate_random_code
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLimit',
            fields=[
                ('credit_limit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_credits', models.IntegerField()),
                ('max_credits', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Credit Limit',
                'verbose_name_plural': 'Credit Limits',
                'db_table': 'credit_limits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255, unique=True)),
                ('department_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=255)),
                ('major_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
                'db_table': 'majors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_code', models.CharField(default=helper.generate_random_code.generate_random_code, max_length=20, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('face_embedding', models.BinaryField(blank=True, null=True)),
                ('profile_attachments', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Suspended')], default='A', max_length=1)),
                ('is_graduated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('student_subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('max_leave_days', models.IntegerField()),
                ('registration_status', models.CharField(default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Subject',
                'verbose_name_plural': 'Student Subjects',
                'db_table': 'student_subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubjectRegistrationRequest',
            fields=[
                ('subject_registration_request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_registration_request_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('reason', models.TextField(null=True)),
                ('status', models.CharField(default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('is_over_credit_limit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subject Registration Request',
                'verbose_name_plural': 'Subject Registration Requests',
                'db_table': 'subject_registration_requests',
                'managed': True,
            },
        ),
    ]
