# Generated by Django 5.2.3 on 2025-09-22 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('students', '0002_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectregistrationrequest',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schedule'),
        ),
        migrations.AlterField(
            model_name='subjectregistrationrequest',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.semester'),
        ),
        migrations.AlterField(
            model_name='subjectregistrationrequest',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='subjectregistrationrequest',
            index=models.Index(fields=['schedule_id'], name='subject_reg_schedul_2e19f2_idx'),
        ),
    ]
