# Generated by Django 5.2.3 on 2025-09-19 16:12

import helper.generate_random_code
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('class_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('class_student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_status', models.CharField(default='auto', max_length=20)),
            ],
            options={
                'verbose_name': 'Class Student',
                'verbose_name_plural': 'Class Students',
                'db_table': 'class_students',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('repeat_weekly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lesson_type', models.CharField(max_length=50)),
                ('day_of_week', models.IntegerField(null=True)),
                ('status', models.CharField(default='1', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'managed': True,
            },
        ),
    ]
