# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('rooms', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.academicyear'),
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='classes.class'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='registered_by_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='students.student'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.lessonslot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['department_id'], name='classes_departm_98bb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year_id'], name='classes_academi_c56e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['class_id'], name='class_stude_class_i_05f053_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['student_id'], name='class_stude_student_a2eaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['registered_by_account_id'], name='class_stude_registe_3e129b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['class_id'], name='schedules_class_i_bf9668_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['subject_id'], name='schedules_subject_3d2967_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['room_id'], name='schedules_room_id_3a02e7_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['slot_id'], name='schedules_slot_id_481994_idx'),
        ),
    ]
