# Generated by Django 5.2.3 on 2025-09-19 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Permission Metadata',
                'verbose_name_plural': 'Permissions Metadata',
                'db_table': 'permission_meta',
            },
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
