CREATE TABLE "face_recognition_logs" (
	"face_recognition_log_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"student_id" BIGINT NOT NULL,
	"face_image_url" TEXT NOT NULL,
	"embedding_matched" CHAR(1) NOT NULL,
	"confidence_score" DECIMAL NOT NULL,
	"model_version" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"attendace_id" BIGINT NOT NULL,
	"note" TEXT,
	PRIMARY KEY("face_recognition_log_id")
);




CREATE TABLE "accounts" (
	"account_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"role_id" BIGINT NOT NULL,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL,
	"is_active" CHAR(1) NOT NULL,
	"phone_number" CHAR(10) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"last_login_at" TIMESTAMP,
	"avatar_url" TEXT,
	"deleted_at" TIMESTAMP,
	"is_locked" CHAR(1) NOT NULL DEFAULT '0',
	"is_verified_email" CHAR(1) NOT NULL DEFAULT '0',
	"user_type" VARCHAR(50) NOT NULL,
	"is_staff" BOOLEAN NOT NULL DEFAULT False,
	PRIMARY KEY("account_id")
);


CREATE INDEX "accounts_index_0"
ON "accounts" ("role_id");

CREATE TABLE "roles" (
	"role_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"role_name" VARCHAR(50) NOT NULL,
	"role_code" VARCHAR(20) NOT NULL UNIQUE,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("role_id")
);




CREATE TABLE "students" (
	"student_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"student_code" CHAR(10) NOT NULL UNIQUE,
	"fullname" VARCHAR(150) NOT NULL,
	"face_embedding" BYTEA,
	"department_id" BIGINT NOT NULL,
	"profile_attachments" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"account_id" BIGINT NOT NULL,
	"gender" CHAR(1) NOT NULL,
	"dob" DATE NOT NULL,
	"status" CHAR(1) NOT NULL DEFAULT '0',
	"is_graduated" CHAR(1) NOT NULL DEFAULT '1',
	"major_id" BIGINT NOT NULL,
	PRIMARY KEY("student_id")
);


CREATE INDEX "students_index_0"
ON "students" ("department_id", "account_id");

CREATE TABLE "permissions" (
	"permission_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"entity_name" VARCHAR(255) NOT NULL,
	"field_name" VARCHAR(100) NOT NULL,
	"read" CHAR(1) NOT NULL DEFAULT '0',
	"insert" CHAR(1) NOT NULL,
	"delete" CHAR(1) NOT NULL,
	"update" CHAR(1) NOT NULL,
	"create_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"account_id" BIGINT NOT NULL,
	"role_id" BIGINT NOT NULL,
	PRIMARY KEY("permission_id")
);




CREATE TABLE "departments" (
	"department_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"department_code" VARCHAR(20) NOT NULL,
	"department_name" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("department_id")
);




CREATE TABLE "classes" (
	"class_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"class_name" VARCHAR(255) NOT NULL UNIQUE,
	"department_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"academic_year_id" BIGINT NOT NULL,
	"class_code" VARCHAR(20) NOT NULL,
	"status" CHAR(1) NOT NULL,
	PRIMARY KEY("class_id")
);


CREATE INDEX "classes_index_0"
ON "classes" ("department_id", "academic_year_id");

CREATE TABLE "schedules" (
	"slot_id" BIGINT NOT NULL,
	"schedule_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"class_id" BIGINT NOT NULL,
	"start_time" TIMESTAMP NOT NULL,
	"end_time" TIMESTAMP NOT NULL,
	"repeat_weekly" CHAR(1) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"subject_id" BIGINT NOT NULL,
	"room_id" BIGINT NOT NULL,
	"latitude" DOUBLE PRECISION NOT NULL,
	"longitude" DOUBLE PRECISION NOT NULL,
	"lesson_type" VARCHAR(255) NOT NULL,
	"day_of_week" INTEGER,
	"status" CHAR(1) NOT NULL DEFAULT '1',
	PRIMARY KEY("schedule_id")
);


CREATE INDEX "schedules_index_0"
ON "schedules" ("class_id", "room_id", "subject_id");

CREATE TABLE "rooms" (
	"room_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"room_name" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"latitude" DECIMAL NOT NULL,
	"longitude" DECIMAL NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"room_code" VARCHAR(20) NOT NULL,
	"room_type" VARCHAR(20) NOT NULL,
	"capacity" INTEGER NOT NULL,
	PRIMARY KEY("room_id")
);




CREATE TABLE "attendance" (
	"checkin_device_id" BIGINT NOT NULL,
	"schedule_id" BIGINT NOT NULL,
	"student_id" BIGINT NOT NULL,
	"attendance_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"status" CHAR(1) NOT NULL,
	"checkin_time" TIMESTAMP NOT NULL,
	"face_image_url" TEXT NOT NULL,
	"verified_by_ai" CHAR(1) NOT NULL,
	"checkin_lat" DECIMAL NOT NULL,
	"checkin_long" DECIMAL NOT NULL,
	"note" TEXT,
	"attendance_type" CHAR(1) NOT NULL,
	"is_late" CHAR(1) NOT NULL DEFAULT '0',
	"late_reason" TEXT,
	"checkin_method" CHAR(10) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("attendance_id")
);




CREATE TABLE "leave_requests" (
	"leave_request_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"subject_id" BIGINT NOT NULL,
	"reason" TEXT NOT NULL,
	"from_date" TIMESTAMP NOT NULL,
	"to_date" TIMESTAMP NOT NULL,
	"status" CHAR(1) NOT NULL,
	"attachment" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"student_id" BIGINT NOT NULL,
	"approved_by" BIGINT NOT NULL,
	"rejected_reason" TEXT,
	"reviewed_at" TIMESTAMP,
	PRIMARY KEY("leave_request_id")
);




CREATE TABLE "reminders" (
	"reminder_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255) NOT NULL,
	"content" TEXT NOT NULL,
	"start_date" TIMESTAMP NOT NULL,
	"end_date" TIMESTAMP NOT NULL,
	"email_notification" CHAR(1) NOT NULL,
	"time_reminder" TIME,
	"subject_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"student_id" BIGINT NOT NULL,
	PRIMARY KEY("reminder_id")
);


CREATE INDEX "reminders_index_0"
ON "reminders" ("subject_id", "academic_year_id");

CREATE TABLE "subjects" (
	"subject_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"subject_name" VARCHAR(255) NOT NULL,
	"department_id" BIGINT NOT NULL,
	"status" CHAR(1) NOT NULL,
	"academic_year_id" BIGINT NOT NULL,
	"subject_code" VARCHAR(20) NOT NULL UNIQUE,
	"total_credits" INTEGER NOT NULL,
	"theoretical_credits" INTEGER NOT NULL DEFAULT 0,
	"practical_credits" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("subject_id")
);




CREATE TABLE "academic_years" (
	"academic_year_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"academic_year_name" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"academic_year_code" VARCHAR(20) NOT NULL,
	PRIMARY KEY("academic_year_id")
);




CREATE TABLE "notifications" (
	"notification_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255) NOT NULL,
	"content" TEXT NOT NULL,
	"created_by" BIGINT NOT NULL,
	"is_read" CHAR(1) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"to_target_id" BIGINT NOT NULL,
	PRIMARY KEY("notification_id")
);


CREATE INDEX "notifications_index_0"
ON "notifications" ("created_by");

CREATE TABLE "devices" (
	"student_id" BIGINT NOT NULL,
	"device_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"device_name" VARCHAR(255) NOT NULL,
	"ip" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"user_agent" VARCHAR(255) NOT NULL,
	PRIMARY KEY("device_id")
);




CREATE TABLE "students_subjects" (
	"students_subject_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"subject_id" BIGINT NOT NULL,
	"student_id" BIGINT NOT NULL,
	"max_leave_days" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"semester_id" BIGINT NOT NULL,
	"registration_status" CHAR(20) NOT NULL DEFAULT 'auto',
	"registered_by_account" BIGINT NOT NULL,
	PRIMARY KEY("students_subject_id")
);




CREATE TABLE "lecturers" (
	"lecturer_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fullname" VARCHAR(255) NOT NULL,
	"account_id" BIGINT NOT NULL,
	"department_id" BIGINT NOT NULL,
	"gender" CHAR(1) NOT NULL,
	"dob" DATE NOT NULL,
	"phone_number" CHAR(10) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("lecturer_id")
);


CREATE INDEX "lecturers_index_0"
ON "lecturers" ("account_id", "department_id");

CREATE TABLE "lecturer_subjects" (
	"lecturer_subject_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"subject_id" BIGINT NOT NULL,
	"lecturer_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("lecturer_subject_id")
);




CREATE TABLE "audit_logs" (
	"log_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"operation" CHAR(1) NOT NULL,
	"old_data" JSONB NOT NULL,
	"new_data" JSONB NOT NULL,
	"changed_by" BIGINT NOT NULL,
	"changed_at" TIMESTAMP NOT NULL,
	"ip_address" VARCHAR(255) NOT NULL,
	"user_agent" VARCHAR(255) NOT NULL,
	"record_id" BIGINT NOT NULL,
	"entity_id" BIGINT NOT NULL,
	"entity_name" VARCHAR(100) NOT NULL,
	"action_description" TEXT,
	PRIMARY KEY("log_id")
);


CREATE INDEX "audit_logs_index_0"
ON "audit_logs" ("changed_by");

CREATE TABLE "class_students" (
	"class_student_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"class_id" BIGINT NOT NULL,
	"student_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"is_active" CHAR(1) NOT NULL DEFAULT '0',
	"registration_status" CHAR(20) NOT NULL DEFAULT 'auto',
	"registered_by_account" BIGINT NOT NULL,
	PRIMARY KEY("class_student_id")
);


CREATE INDEX "class_students_index_0"
ON "class_students" ("class_id", "student_id");

CREATE TABLE "majors" (
	"department_id" BIGINT NOT NULL,
	"major_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"major_name" VARCHAR(255) NOT NULL,
	"major_code" VARCHAR(20) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("major_id")
);




CREATE TABLE "semesters" (
	"semester_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"semester_name" VARCHAR(255) NOT NULL,
	"start_date" DATE NOT NULL,
	"end_date" DATE NOT NULL,
	"academic_year_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"semester_code" VARCHAR(20) NOT NULL,
	"status" CHAR(1) NOT NULL,
	PRIMARY KEY("semester_id")
);


CREATE INDEX "semesters_index_0"
ON "semesters" ("academic_year_id");

CREATE TABLE "qr_checkin" (
	"qr_checkin_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"qr_code" VARCHAR(255) NOT NULL UNIQUE,
	"created_by" BIGINT NOT NULL,
	"schedule_id" BIGINT NOT NULL,
	"expire_at" TIMESTAMP NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"used_by_student_id" BIGINT NOT NULL,
	"is_active" CHAR(1) NOT NULL,
	"usage_count" INTEGER NOT NULL,
	"max_usage" INTEGER NOT NULL,
	"radius" INTEGER NOT NULL,
	"latitude" DOUBLE PRECISION NOT NULL,
	"longitude" DOUBLE PRECISION NOT NULL,
	PRIMARY KEY("qr_checkin_id")
);




CREATE TABLE "subject_registration_requests" (
	"schedule_id" BIGINT NOT NULL,
	"student_id" BIGINT NOT NULL,
	"reason" TEXT,
	"subject_registration_request_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"status" VARCHAR(100) NOT NULL DEFAULT 'pending',
	"created_at" TIMESTAMP NOT NULL,
	"reviewed_at" TIMESTAMP NOT NULL,
	"is_over_credit_limit" BOOLEAN NOT NULL DEFAULT false,
	"approved_by" BIGINT NOT NULL,
	PRIMARY KEY("subject_registration_request_id")
);


CREATE INDEX "subject_registration_requests_index_0"
ON "subject_registration_requests" ("student_id", "semester_id", "subject_id");

CREATE TABLE "attendance_verifications" (
	"attendance_id" BIGINT NOT NULL,
	"verification_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"lecturer_id" BIGINT NOT NULL,
	"verified_at" TIMESTAMP NOT NULL,
	"status" CHAR(1) NOT NULL DEFAULT '1',
	"note" TEXT,
	PRIMARY KEY("verification_id")
);




CREATE TABLE "credit_limits" (
	"credit_limit_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"student_id" BIGINT NOT NULL,
	"semester_id" BIGINT,
	"min_credits" INTEGER NOT NULL,
	"max_credits" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("credit_limit_id")
);




CREATE TABLE "staffs" (
	"account_id" BIGINT NOT NULL,
	"fullname" VARCHAR(255) NOT NULL,
	"staff_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"department_id" BIGINT NOT NULL,
	"gender" CHAR(1) NOT NULL,
	"dob" DATE NOT NULL,
	"phone_number" CHAR(10) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("staff_id")
);




CREATE TABLE "import_logs" (
	"import_log_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"staff_id" BIGINT NOT NULL,
	"file_name" VARCHAR(255) NOT NULL,
	"import_type" VARCHAR(255) NOT NULL,
	"status" CHAR(1) NOT NULL,
	"error_report" TEXT,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("import_log_id")
);




CREATE TABLE "shifts" (
	"shift_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"shift_name" VARCHAR(255) NOT NULL,
	"start_time" TIME NOT NULL,
	"end_time" TIME NOT NULL,
	"status" CHAR(1) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("shift_id")
);




CREATE TABLE "login_logs" (
	"log_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"account_id" BIGINT NOT NULL,
	"login_time" TIMESTAMP NOT NULL,
	"ip_address" VARCHAR(100) NOT NULL,
	"user_agent" TEXT NOT NULL,
	"device_info" TEXT NOT NULL,
	PRIMARY KEY("log_id")
);




CREATE TABLE "subject_classes" (
	"subject_class_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"subject_id" BIGINT NOT NULL,
	"class_id" BIGINT NOT NULL,
	"lecturer_id" BIGINT NOT NULL,
	"semester_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("subject_class_id")
);




CREATE TABLE "lesson_slots" (
	"shift_id" BIGINT NOT NULL,
	"slot_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"slot_name" VARCHAR(255) NOT NULL,
	"start_time" TIME NOT NULL,
	"end_time" TIME NOT NULL,
	"duration_minutes" INTEGER NOT NULL,
	PRIMARY KEY("slot_id")
);




CREATE TABLE "contacts" (
	"contact_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"account_id" BIGINT NOT NULL,
	"type_person_contact" CHAR(10) NOT NULL,
	"assigned_to" BIGINT NOT NULL,
	"subject" VARCHAR(255) NOT NULL,
	"message" TEXT NOT NULL,
	"response" TEXT,
	"status" CHAR(20) NOT NULL DEFAULT 'new',
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("contact_id")
);



ALTER TABLE "accounts"
ADD FOREIGN KEY("role_id") REFERENCES "roles"("role_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "students"
ADD FOREIGN KEY("account_id") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "permissions"
ADD FOREIGN KEY("role_id") REFERENCES "roles"("role_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "students"
ADD FOREIGN KEY("department_id") REFERENCES "departments"("department_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "classes"
ADD FOREIGN KEY("department_id") REFERENCES "departments"("department_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "schedules"
ADD FOREIGN KEY("room_id") REFERENCES "rooms"("room_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "attendance"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "subjects"
ADD FOREIGN KEY("department_id") REFERENCES "departments"("department_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reminders"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "subjects"
ADD FOREIGN KEY("academic_year_id") REFERENCES "academic_years"("academic_year_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "leave_requests"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "devices"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "schedules"
ADD FOREIGN KEY("class_id") REFERENCES "classes"("class_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "schedules"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lecturers"
ADD FOREIGN KEY("account_id") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lecturers"
ADD FOREIGN KEY("department_id") REFERENCES "departments"("department_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lecturer_subjects"
ADD FOREIGN KEY("lecturer_id") REFERENCES "lecturers"("lecturer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lecturer_subjects"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "audit_logs"
ADD FOREIGN KEY("changed_by") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "leave_requests"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "students_subjects"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "students_subjects"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "attendance"
ADD FOREIGN KEY("checkin_device_id") REFERENCES "devices"("device_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "class_students"
ADD FOREIGN KEY("class_id") REFERENCES "classes"("class_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "class_students"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "leave_requests"
ADD FOREIGN KEY("approved_by") REFERENCES "lecturers"("lecturer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "classes"
ADD FOREIGN KEY("academic_year_id") REFERENCES "academic_years"("academic_year_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "students"
ADD FOREIGN KEY("major_id") REFERENCES "majors"("major_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "students_subjects"
ADD FOREIGN KEY("semester_id") REFERENCES "semesters"("semester_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "semesters"
ADD FOREIGN KEY("academic_year_id") REFERENCES "academic_years"("academic_year_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "qr_checkin"
ADD FOREIGN KEY("schedule_id") REFERENCES "schedules"("schedule_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "qr_checkin"
ADD FOREIGN KEY("created_by") REFERENCES "lecturers"("lecturer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "attendance_verifications"
ADD FOREIGN KEY("attendance_id") REFERENCES "attendance"("attendance_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lecturers"
ADD FOREIGN KEY("lecturer_id") REFERENCES "attendance_verifications"("verification_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "semesters"
ADD FOREIGN KEY("semester_id") REFERENCES "credit_limits"("semester_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "subject_registration_requests"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "qr_checkin"
ADD FOREIGN KEY("used_by_student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reminders"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "credit_limits"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "face_recognition_logs"
ADD FOREIGN KEY("student_id") REFERENCES "students"("student_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "majors"
ADD FOREIGN KEY("department_id") REFERENCES "departments"("department_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "staffs"
ADD FOREIGN KEY("account_id") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "import_logs"
ADD FOREIGN KEY("staff_id") REFERENCES "staffs"("staff_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "login_logs"
ADD FOREIGN KEY("account_id") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "subject_classes"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "classes"
ADD FOREIGN KEY("class_id") REFERENCES "subject_classes"("class_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "subject_classes"
ADD FOREIGN KEY("lecturer_id") REFERENCES "lecturers"("lecturer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "subject_classes"
ADD FOREIGN KEY("semester_id") REFERENCES "semesters"("semester_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "shifts"
ADD FOREIGN KEY("shift_id") REFERENCES "lesson_slots"("shift_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lesson_slots"
ADD FOREIGN KEY("slot_id") REFERENCES "schedules"("slot_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications"
ADD FOREIGN KEY("created_by") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications"
ADD FOREIGN KEY("to_target_id") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "accounts"
ADD FOREIGN KEY("account_id") REFERENCES "subject_registration_requests"("approved_by")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "schedules"
ADD FOREIGN KEY("schedule_id") REFERENCES "subject_registration_requests"("schedule_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;