# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['account_id'], name='staffs_account_8c68ee_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department_id'], name='staffs_departm_ccdf81_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['staff_id'], name='import_logs_staff_i_31ee0b_idx'),
        ),
    ]
