# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.core.serializers.json
import django.db.models.deletion
import helper.generate_random_code
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('operation', models.CharField(choices=[('C', 'Create'), ('R', 'Read'), ('U', 'Update'), ('D', 'Delete')], max_length=1)),
                ('old_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('new_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('record_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['changed_by'], name='audit_logs_changed_310180_idx'), models.Index(fields=['entity_name'], name='audit_logs_entity__859b8a_idx'), models.Index(fields=['changed_at'], name='audit_logs_changed_35eb1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('login_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Failed')], default='S', max_length=1)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'db_table': 'login_logs',
                'indexes': [models.Index(fields=['account'], name='login_logs_account_a9fd47_idx'), models.Index(fields=['status'], name='login_logs_status_c0c84b_idx'), models.Index(fields=['login_time'], name='login_logs_login_t_bc25ca_idx')],
            },
        ),
    ]
