# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.db.models.deletion
import helper.generate_random_code
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('academic_year_name', models.CharField(max_length=255)),
                ('academic_year_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('shift_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'shifts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('semester_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.academicyear')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semesters',
                'managed': True,
                'indexes': [models.Index(fields=['academic_year_id'], name='semesters_academi_47be9a_idx'), models.Index(fields=['status'], name='semesters_status_abd5d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('slot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('slot_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.shift')),
            ],
            options={
                'verbose_name': 'Lesson Slot',
                'verbose_name_plural': 'Lesson Slots',
                'db_table': 'lesson_slots',
                'managed': True,
                'indexes': [models.Index(fields=['shift_id'], name='lesson_slot_shift_i_109ce3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
                ('subject_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('theoretical_credits', models.IntegerField()),
                ('practical_credits', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sessions_per_class', models.IntegerField(null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'managed': True,
                'indexes': [models.Index(fields=['department_id'], name='subjects_departm_26ad56_idx'), models.Index(fields=['academic_year_id'], name='subjects_academi_6ef194_idx')],
            },
        ),
    ]
