# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.db.models.deletion
import helper.generate_random_code
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerSubject',
            fields=[
                ('lecturer_subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lecturer Subject',
                'verbose_name_plural': 'Lecturer Subjects',
                'db_table': 'lecturer_subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('subject_class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Class',
                'verbose_name_plural': 'Subject Classes',
                'db_table': 'subject_classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lecturer_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
                'db_table': 'lecturers',
                'managed': True,
            },
        ),
    ]
