# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('lecturers', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
        migrations.AddField(
            model_name='lecturersubject',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer'),
        ),
        migrations.AddField(
            model_name='lecturersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='classes.class'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.semester'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['account_id'], name='lecturers_account_9bca51_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['department_id'], name='lecturers_departm_77f381_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturersubject',
            index=models.Index(fields=['subject_id'], name='lecturer_su_subject_d130f9_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturersubject',
            index=models.Index(fields=['lecturer_id'], name='lecturer_su_lecture_068b11_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['subject_id'], name='subject_cla_subject_d1721f_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['class_id'], name='subject_cla_class_i_46d91d_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['lecturer_id'], name='subject_cla_lecture_aaf44e_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['semester_id'], name='subject_cla_semeste_ec1af0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together={('subject', 'class_id', 'lecturer', 'semester')},
        ),
    ]
