# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.db.models.deletion
import helper.generate_random_code
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reminder_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('email_notification', models.CharField(choices=[('P', 'Pending'), ('S', 'Sended'), ('E', 'Error'), ('U', 'Success')], default='P', max_length=1)),
                ('status_send_email', models.CharField(choices=[('P', 'Pending'), ('S', 'Sended'), ('E', 'Error'), ('U', 'Success')], default='P', max_length=1)),
                ('sms_notification', models.CharField(choices=[('P', 'Pending'), ('S', 'Sended'), ('E', 'Error'), ('U', 'Success')], default='S', max_length=1)),
                ('status_send_sms', models.CharField(choices=[('P', 'Pending'), ('S', 'Sended'), ('E', 'Error'), ('U', 'Success')], default='S', max_length=1)),
                ('time_reminder', models.TimeField(default='00:30:00')),
                ('status_reminder', models.CharField(choices=[('P', 'Pending'), ('S', 'Sended'), ('E', 'Error'), ('U', 'Success')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'reminders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_read', models.CharField(default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('to_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'managed': True,
            },
        ),
    ]
