# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_by'], name='notificatio_created_336cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['to_target'], name='notificatio_to_targ_77bad6_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['subject_id'], name='reminders_subject_8954af_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['student_id'], name='reminders_student_f65308_idx'),
        ),
    ]
