# Generated by Django 5.2.3 on 2025-09-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
