# Generated by Django 5.2.3 on 2025-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_reminder_end_date_alter_reminder_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='application_notification',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('S', 'Sended'), ('E', 'Error'), ('U', 'Success')], default='P', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='status_send_application',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('S', 'Sended'), ('E', 'Error'), ('U', 'Success')], default='P', max_length=1, null=True),
        ),
    ]
