# Generated by Django 5.2.3 on 2025-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_reminder_application_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sent_email_1h_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when 1-hour-before email was sent.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sent_email_30m_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when 30-minute-before email was sent.', null=True),
        ),
    ]
