# Generated by Django 5.2.3 on 2025-09-19 16:12

import helper.generate_random_code
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('status', models.CharField(choices=[('P', 'Có mặt'), ('A', 'Vắng'), ('L', 'Đi muộn')], default='P', max_length=1)),
                ('attendance_type', models.CharField(choices=[('F', 'Nhận diện khuôn mặt'), ('Q', 'Quét QR')], max_length=1)),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('face_image_url', models.URLField(blank=True, null=True)),
                ('verified_by_ai', models.BooleanField(default=False)),
                ('checkin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_reason', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendances',
            },
        ),
        migrations.CreateModel(
            name='AttendanceVerification',
            fields=[
                ('verification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Chờ xác nhận'), ('A', 'Đã xác nhận'), ('R', 'Từ chối')], default='P', max_length=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Verification',
                'verbose_name_plural': 'Attendance Verifications',
                'db_table': 'attendance_verifications',
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('face_recognition_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('face_embedding', models.BinaryField()),
                ('face_image_url', models.TextField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Face Recognition Log',
                'verbose_name_plural': 'Face Recognition Logs',
                'db_table': 'face_recognition_logs',
            },
        ),
        migrations.CreateModel(
            name='QRCheckin',
            fields=[
                ('qr_checkin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('qr_image_url', models.URLField(blank=True, null=True)),
                ('expire_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_usage', models.IntegerField(default=1)),
                ('radius', models.IntegerField(default=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'QR Checkin',
                'verbose_name_plural': 'QR Checkins',
                'db_table': 'qr_checkins',
            },
        ),
        migrations.CreateModel(
            name='QRCheckinLog',
            fields=[
                ('qr_checkin_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'QR Checkin Log',
                'verbose_name_plural': 'QR Checkin Logs',
                'db_table': 'qr_checkin_logs',
            },
        ),
    ]
