# Generated by Django 5.2.3 on 2025-09-19 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('classes', '0001_initial'),
        ('lecturers', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.device'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceverification',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='attendanceverification',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer'),
        ),
        migrations.AddField(
            model_name='facerecognitionlog',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='facerecognitionlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='qrcheckin',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer'),
        ),
        migrations.AddField(
            model_name='qrcheckin',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schedule'),
        ),
        migrations.AddField(
            model_name='qrcheckinlog',
            name='qr_checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.qrcheckin'),
        ),
        migrations.AddField(
            model_name='qrcheckinlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['schedule', 'student'], name='attendances_schedul_51c919_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['checkin_device'], name='attendances_checkin_8a3486_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceverification',
            index=models.Index(fields=['attendance', 'lecturer'], name='attendance__attenda_2af666_idx'),
        ),
        migrations.AddIndex(
            model_name='facerecognitionlog',
            index=models.Index(fields=['attendance'], name='face_recogn_attenda_09e501_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['schedule'], name='qr_checkins_schedul_624ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['created_by'], name='qr_checkins_created_7e5fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckinlog',
            index=models.Index(fields=['qr_checkin', 'student'], name='qr_checkin__qr_chec_62be93_idx'),
        ),
    ]
